### ISSUE TITLE
Store Information

### ISSUE THREAD

**Issue by prithvilalla** [mpuckett13/MasGrocerySosSp16#8]
I have created the front end with the following parameters:
Store Name:
Phone:
Street Address:
City:
State:
Zip:

I will add the fields Company: Website: and Email: but it will make my work much easier if you can split the Address field into multiple sub fields like street address, city, state and zip. Otherwise, I will have to use a lot of string manipulations to make it in the correct format. If that's not possible, I'll modify the front end to just display the address field as a string and modify it as it is.

**Comment by prithvilalla** [comment]
Furthermore, for testing purpose and since it should also be compulsory, can you add some garbage entry for the store "teststore" for the fields mentioned above. I want to grab these fields from the database and display them on the manager screen
<img width="369" alt="screen shot 2016-03-22 at 1 31 11 am" src="https://cloud.githubusercontent.com/assets/11687922/13942893/cdeb86d4-efcd-11e5-8fae-afacee9b531c.png">

**Comment by bnewcomer** [comment]
Right now you should be able to submit store data in the following format:

```js
var data = {
		name: 'test',
		address: {
			street: '123 main street',
			city: 'atlanta',
			state : 'GA',
			zip: '12345'
		},
		company: 'testcompany'
	};

That should address the first issue. I will add data for all fields for the test store to the seed file in /scripts/seed.js and close the issue when I have pushed the code.
